### ISSUE TITLE
How is this tool working?

### ISSUE THREAD

**Issue by tonyqus** [SeanKilleen/dotnet-ecosystem#7]
I'd like to understand how this tool works because I'm also working on analyzing the .NET ecosystem.

Does this tool crawl the nuget website or at least the dependencies and used by of one project?

**Comment by SeanKilleen** [comment]
The purpose of this tool is to analyze a bunch of local folders to see all of the dependencies for all of the projects contained within them.

You can see how it works by looking at the source code, or by running it according to the readme 👍.

It was a quick tool written to help a former colleague, and is a stepping stone toward some of the work I'm planning around OSS understanding and sustainability. (that work will first take the form of an impact map, and then some official tooling with a roadmap that I'll build out in the open.)
